Skip to content
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
adobe weedmaps
Repositories0
Code237
Commits0
Issues0
Marketplace0
Topics0
Wikis0
Users0
Language

Sort

Showing 234 available code results 
@N3BB3Z4R
N3BB3Z4R/fnkfnk – form-u1597.php
Showing the top three matches
Last indexed on Jul 8, 2018
PHP
PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario SIGN',
		'from' => 'nebe@weedmaps.com',
		'to' => 'nebe@weedmaps.com'
	),
	'fields' => array(
		'custom_U1606' => array(
@N3BB3Z4R
N3BB3Z4R/fnkfnk – form-u809.php
Showing the top three matches
Last indexed on Jul 8, 2018
PHP
PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'email' => array(
		'from' => 'nebe@weedmaps.com',
		'to' => 'nebe@weedmaps.com'
	),
	'fields' => array(
@haonanc
haonanc/GDPR-data-collection – 2359 weedmaps.com.txt
Showing the top match
Last indexed on Oct 8, 2018
Text
1. General Statements
Welcome to the Weedmaps family of sites and software! This Privacy Policy is a legally binding contract between Ghost Management Group, LLC or its applicable affiliate that owns or controls the applicable Website or provides the applicable Services that you may be accessing or using (“Weedmaps”, “us”, “we” or “our”), on the one hand, and you and your successors and heirs and (if applicable) the corporate entity you represent (“you” or “your”), on the other hand. This Privacy Policy describes our policies on the collection, use, and disclosure of information when you access or use Weedmaps’ (a) websites, portals, mobile applications, channels, and software, including weedmaps.com, marijuana.com, mmjmenu.com, cannabis.com, and safeaccessmd.com, and (b) social media pages and channels (collectively, the “Websites”), including any services, features, media, functions, content, tools, and links contained or offered therein (collectively, the “Services”). When you use the Websites or Services, you consent to our collection, use, modification, and disclosure of information about you as described in this Privacy Policy. If you do not accept and agree to this Privacy Policy, you may not access or use any of the Websites or Services or create an account or user profile.
@haonanc
haonanc/GDPR-data-collection – 2751 marijuana.com.txt
Showing the top match
Last indexed on Oct 8, 2018
Text
Welcome! You have arrived at a web site or mobile application that is provided by WeedMaps Media, Inc. (“WeedMaps” or “we,” “our” or “us”). This “Privacy Policy” governs your use of  www.weedmaps.com ,  www.marijuana.com  and any other official WeedMaps web site (including mobile sites), mobile application, interactive features, widgets, and/or other online services that post a link to this Privacy Policy (collectively, referred to as the “Service”), regardless of how you access or use the Service, whether via personal computers, mobile devices or otherwise. This Privacy Policy does not apply to our data collection activities offline or otherwise outside of our Service (unless otherwise stated below).
@mcelaney
mcelaney/fawkes – speaker.ex
Showing the top two matches
Last indexed on Aug 18, 2018
Elixir
          "This session is co-presented by Bailey Miller and Tim Mecklem. Bailey creates amazing things as a designer at Gaslight (teamgaslight.com) and has written about her experience working with Phoenix from a front end developer perspective. Tim is a developer at Gaslight, where he builds exciting software and helps people build themselves. They have presented separately at conferences like Adobe Jam and ElixirConf, and this is their first time teaming up to show how design and development complement each other."
        first: "Todd",
        last: "Resudek",
        company: "Weedmaps",
        github: "supersimple",
@nhu313
nhu313/fawkes_nhu – speaker.ex
Showing the top two matches
Last indexed on Aug 25, 2018
Elixir
        description: "This session is co-presented by Bailey Miller and Tim Mecklem. Bailey creates amazing things as a designer at Gaslight (teamgaslight.com) and has written about her experience working with Phoenix from a front end developer perspective. Tim is a developer at Gaslight, where he builds exciting software and helps people build themselves. They have presented separately at conferences like Adobe Jam and ElixirConf, and this is their first time teaming up to show how design and development complement each other."
        last: "Resudek",
        company: "Weedmaps",
        github: "supersimple",
        description: "I am a reformed graphic designer that got my start in web development 15 years ago. I have made a career in front-end development, PHP, Rails, and for the last year or so, in Elixir. I am a contributor to hex and hex.pm and in my spare time I tinker with hardware projects."
@PhoenixBasics
PhoenixBasics/phoenix_basics – speaker.ex
Showing the top two matches
Last indexed on Sep 7, 2018
Elixir
          "This session is co-presented by Bailey Miller and Tim Mecklem. Bailey creates amazing things as a designer at Gaslight (teamgaslight.com) and has written about her experience working with Phoenix from a front end developer perspective. Tim is a developer at Gaslight, where he builds exciting software and helps people build themselves. They have presented separately at conferences like Adobe Jam and ElixirConf, and this is their first time teaming up to show how design and development complement each other."
        last: "Resudek",
        company: "Weedmaps",
        github: "supersimple",
        twitter: "sprsmpl",
@etagwerker
etagwerker/phoenix-test – speaker.ex
Showing the top two matches
Last indexed on Aug 25, 2018
Elixir
        description: "This session is co-presented by Bailey Miller and Tim Mecklem. Bailey creates amazing things as a designer at Gaslight (teamgaslight.com) and has written about her experience working with Phoenix from a front end developer perspective. Tim is a developer at Gaslight, where he builds exciting software and helps people build themselves. They have presented separately at conferences like Adobe Jam and ElixirConf, and this is their first time teaming up to show how design and development complement each other."
        last: "Resudek",
        company: "Weedmaps",
        github: "supersimple",
        description: "I am a reformed graphic designer that got my start in web development 15 years ago. I have made a career in front-end development, PHP, Rails, and for the last year or so, in Elixir. I am a contributor to hex and hex.pm and in my spare time I tinker with hardware projects."
@nhu313
nhu313/phoenix_basic – speaker.ex
Showing the top two matches
Last indexed on Aug 17, 2018
Elixir
        description: "This session is co-presented by Bailey Miller and Tim Mecklem. Bailey creates amazing things as a designer at Gaslight (teamgaslight.com) and has written about her experience working with Phoenix from a front end developer perspective. Tim is a developer at Gaslight, where he builds exciting software and helps people build themselves. They have presented separately at conferences like Adobe Jam and ElixirConf, and this is their first time teaming up to show how design and development complement each other."
        image: image_info("todd-resudek.jpg"),
        first: "Todd",
        last: "Resudek",
        company: "Weedmaps",
        github: "supersimple",
@Verean
Verean/Evoc – appfilter.xml
Showing the top three matches
Last indexed on Jul 10, 2018
XML
        <item component="ComponentInfo{com.bigtincan.adfree/com.bigtincan.adfree.FreeMe}" drawable="adfree"/>
        <!-- Adobe Flash RIP -->
        <item component="ComponentInfo{com.adobe.flashplayer/com.adobe.flashplayer.SettingsManager}" drawable="adobeflash"/>
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
